import {
	pgTable,
	text,
	timestamp,
	uuid,
	integer,
	numeric,
	jsonb,
} from 'drizzle-orm/pg-core';

/** Core profile row — Clerk `user_id`, soft-delete via `account_status`. */
export const profilesCore = pgTable('profiles_core', {
	id: uuid('id').primaryKey().defaultRandom(),
	userId: text('user_id').unique(),
	yaId: text('ya_id'),
	fullName: text('full_name'),
	firstName: text('first_name'),
	middleName: text('middle_name'),
	lastName: text('last_name'),
	photoUrl: text('photo_url'),
	email: text('email'),
	role: text('role').notNull().default('volunteer'),
	qrCodeUrl: text('qr_code_url'),
	accessibleModules: jsonb('accessible_modules'),
	/** active | inactive — soft delete when Clerk user is deleted */
	accountStatus: text('account_status').notNull().default('active'),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const profilesData = pgTable('profiles_data', {
	id: uuid('id').primaryKey().defaultRandom(),
	userId: text('user_id').references(() => profilesCore.userId),
	age: text('age'),
	gender: text('gender'),
	dateOfBirth: text('date_of_birth'),
	maritalStatus: text('marital_status'),
	bloodGroup: text('blood_group'),
	willingBloodDonation: text('willing_blood_donation'),
	imageRemarks: text('image_remarks'),
	imageSavedAs: text('image_saved_as'),
	contactNumber: text('contact_number'),
	alternateContact: text('alternate_contact'),
	whatsappNumber: text('whatsapp_number'),
	emergencyContact: text('emergency_contact'),
	emergencyRelationship: text('emergency_relationship'),
	preferredCommunication: text('preferred_communication'),
	languagesKnown: text('languages_known'),
	emailId: text('email_id'),
	permanentAddress: text('permanent_address'),
	landmark: text('landmark'),
	country: text('country'),
	state: text('state'),
	district: text('district'),
	tehsil: text('tehsil'),
	cityTownVillage: text('city_town_village'),
	postOffice: text('post_office'),
	pinCode: text('pin_code'),
	permanentCenter: text('permanent_center'),
	zonePermanentCenter: text('zone_permanent_center'),
	permanentAddressRemarks: text('permanent_address_remarks'),
	sameAsPermanent: text('same_as_permanent'),
	communicationAddress: text('communication_address'),
	communicationPincode: text('communication_pincode'),
	communicationRemarks: text('communication_remarks'),
	sewaCenter: text('sewa_center'),
	sewaZone: text('sewa_zone'),
	ifInitiated: text('if_initiated'),
	initiatedBy: text('initiated_by'),
	dateOfInitiation: text('date_of_initiation'),
	initiationRemarks: text('initiation_remarks'),
	primarySewaPermanent: text('primary_sewa_permanent'),
	secondarySewaPermanent: text('secondary_sewa_permanent'),
	otherSewaPermanent: text('other_sewa_permanent'),
	primarySewaCurrent: text('primary_sewa_current'),
	secondarySewaCurrent: text('secondary_sewa_current'),
	otherSewaCurrent: text('other_sewa_current'),
	sewaAreaDelhi: text('sewa_area_delhi'),
	highestQualification: text('highest_qualification'),
	graduation: text('graduation'),
	graduationSecondary: text('graduation_secondary'),
	graduationCollege: text('graduation_college'),
	postGraduation: text('post_graduation'),
	postGraduationSecondary: text('post_graduation_secondary'),
	postGraduationCollege: text('post_graduation_college'),
	professionalCourse: text('professional_course'),
	occupationCategory: text('occupation_category'),
	profession: text('profession'),
	professionBusinessName: text('profession_business_name'),
	companyName: text('company_name'),
	jobDesignation: text('job_designation'),
	specialSkills: text('special_skills'),
	permanentIcardStatus: text('permanent_icard_status'),
	miscellaneous: text('miscellaneous'),
	typeOfIcard: text('type_of_icard'),
	icardRemarks: text('icard_remarks'),
	permanentIcardRequest: text('permanent_icard_request'),
	uniform: text('uniform'),
	orientationTraining: text('orientation_training'),
	placeOfOrientation: text('place_of_orientation'),
	dateOfJoining: text('date_of_joining'),
	orientationDateRemarks: text('orientation_date_remarks'),
	yearsInYa: text('years_in_ya'),
	activeStatus: text('active_status'),
	activeStatusUpdatedOn: text('active_status_updated_on'),
	remarks: text('remarks'),
	yaIdRemarks: text('ya_id_remarks'),
	roleResponsibility: text('role_responsibility'),
	roleUpdatedOn: text('role_updated_on'),
	registeredBeone: text('registered_beone'),
	sosUsername: text('sos_username'),
	beoneRemarks: text('beone_remarks'),
	knowsCarDriving: text('knows_car_driving'),
	usingYaEventApp: text('using_ya_event_app'),
	satSandesh: text('sat_sandesh'),
	socialMedia: text('social_media'),
	frontendSewaPreference: text('frontend_sewa_preference'),
	backendSewaPreference: text('backend_sewa_preference'),
	availability: text('availability'),
	sewaTimings: text('sewa_timings'),
	lastUpdatedSheet: text('last_updated_sheet'),
	dataUpdationRemarks: text('data_updation_remarks'),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const profilesSensitive = pgTable('profiles_sensitive', {
	id: uuid('id').primaryKey().defaultRandom(),
	userId: text('user_id').references(() => profilesCore.userId),
	idProofType: text('id_proof_type'),
	idProofRemarks: text('id_proof_remarks'),
	idProofSavedAs: text('id_proof_saved_as'),
	adminNotes: text('admin_notes'),
	backgroundCheckStatus: text('background_check_status'),
	flagStatus: text('flag_status'),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const inventoryItems = pgTable('inventory_items', {
	id: uuid('id').primaryKey().defaultRandom(),
	itemName: text('item_name').notNull(),
	variant: text('variant').default(''),
	currentQuantity: numeric('current_quantity').notNull().default('0'),
	unitPrice: numeric('unit_price').notNull().default('0'),
	unitType: text('unit_type').notNull().default('piece'),
	totalReceived: numeric('total_received').notNull().default('0'),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

/** Supports legacy stock rows and POS rows (nullable columns per flow). */
export const inventoryLogs = pgTable('inventory_logs', {
	id: uuid('id').primaryKey().defaultRandom(),
	volunteerId: uuid('volunteer_id'),
	itemId: uuid('item_id'),
	issuedBy: text('issued_by'),
	status: text('status').notNull().default('issued'),
	quantityIssued: numeric('quantity_issued'),
	amountDue: numeric('amount_due').default('0'),
	paymentMethod: text('payment_method'),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
	legacyUserId: text('user_id'),
	stockItemId: uuid('stock_item_id'),
	itemName: text('item_name'),
	quantity: integer('quantity'),
	year: integer('year'),
	issuedAt: timestamp('issued_at', { withTimezone: true }),
	notes: text('notes'),
});

export const stockItems = pgTable('stock_items', {
	id: uuid('id').primaryKey().defaultRandom(),
	name: text('name').notNull(),
	category: text('category').default('General'),
	description: text('description').default(''),
	totalQuantity: integer('total_quantity').default(0),
	issuedQuantity: integer('issued_quantity').default(0),
	unit: text('unit').default('pcs'),
	minStockLevel: integer('min_stock_level').default(0),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const stockAuditLogs = pgTable('stock_audit_logs', {
	id: uuid('id').primaryKey().defaultRandom(),
	itemId: uuid('item_id').notNull(),
	adjustedBy: text('adjusted_by').notNull(),
	quantityAdded: numeric('quantity_added').notNull(),
	newTotal: numeric('new_total').notNull(),
	notes: text('notes').default(''),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});
